package meico.mei;

import net.sf.saxon.expr.Component;
import nu.xom.Element;
import nu.xom.ParentNode;

import java.util.ArrayList;

/**
 * This class represents an ornaments instruction by managing the notes to played for the very ornament.
 * @author Lars Engeln
 */
public class Instruction {
    private MeiElement element;
    private MeiElement graceGrpElement;
    private MeiElement notesElement;
    private ArrayList<MeiElement> notes;

    private ArrayList<MeiElement> correspondences;

    public Instruction() {
        element                     = new MeiElement("supplied");
        graceGrpElement             = new MeiElement("graceGrp");
        notesElement                = new MeiElement("beam");
        notes                       = new ArrayList<>();
        correspondences             = new ArrayList<>();

        element.appendChild(graceGrpElement);
        graceGrpElement.appendChild(notesElement);

        element.set("evidence", "internal");
        element.set("reason", "generated by meico to give a basic instruction for the ornament's notes");
    }

    public void setLabel(String label) {
        element.set("label", label);
        notesElement.set("label", label);
    }

    public void addCorrespondence(MeiElement note) {
        correspondences.add(note);
        String corresp = "";
        boolean isFirst = true;
        for (MeiElement c : correspondences) {
            String id = Helper.getAttribute("id", c.getElement()).getValue();
            if (!isFirst) corresp += ' ';
            else isFirst = false;
            corresp += '#' + id;
        };

        element.set("corresp", corresp);
    }

    public void addNote(MeiElement note) {
        notes.add(note);
        notesElement.appendChild(note);
    }
    public MeiElement getNote(int index) { return notes.get(index); }
    public ArrayList<MeiElement> getNotes() { return notes; }

    public void removeNote(int index) {
        notes.remove(index);
        notesElement.getElement().removeChild(index);
    }

    public Element getInstructionElement() {
        return element.getElement();
    }

    public MeiElement getNotesElement() {
        return notesElement;
    }

    public void append(Instruction instruction) {
        MeiElement lastNote = notes.get(notes.size()-1);
        MeiElement firstNote = instruction.getNote(0);

        if(lastNote.get("pname").equals(firstNote.get("pname"))
                && lastNote.get("accid.ges").equals(firstNote.get("accid.ges"))) {
            instruction.removeNote(0);
        }

        MeiElement child = instruction.getNotesElement();
        ParentNode parent = child.getElement().getParent();
        if (parent != null) {
            parent.removeChild(child.getElement());
        }
        this.graceGrpElement.appendChild(child);
        element.set("label", element.get("label") + ", " + child.get("label"));
    }
}
