package meico.mei;

import meico.xml.RichElement;
import nu.xom.Element;
import nu.xom.ParentNode;

import java.util.ArrayList;

/**
 * This class represents an ornaments ornamentExpansion by managing the notes to played for the very ornament.
 * @author Lars Engeln
 */
public class OrnamentExpansion {
    private RichElement ornamentExpansionElement;
    private RichElement groupElement;
    private ArrayList<RichElement> notes;

    private ArrayList<RichElement> correspondences;

    public OrnamentExpansion() {
        ornamentExpansionElement          = new RichElement("supplied");
        groupElement                = new RichElement("graceGrp");
        notes                       = new ArrayList<>();
        correspondences             = new ArrayList<>();

        ornamentExpansionElement.appendChild(groupElement);

        ornamentExpansionElement.set("evidence", "internal");
        ornamentExpansionElement.set("reason", "generated by meico to give a basic ornamentExpansion for the ornament's notes");
    }

    public void setLabel(String label) {
        ornamentExpansionElement.set("label", label);
        groupElement.set("label", label);
    }

    public void addCorrespondence(RichElement note) {
        correspondences.add(note);
        String corresp = "";
        boolean isFirst = true;
        for (RichElement c : correspondences) {
            String id = Helper.getAttribute("id", c.getElement()).getValue();
            if (!isFirst) corresp += ' ';
            else isFirst = false;
            corresp += '#' + id;
        };

        ornamentExpansionElement.set("corresp", corresp);
    }

    public void addElement(RichElement element) {
        if(element.getName().equals("note")) {
            element.set("stem.visible", "false");
            notes.add(element);
        }
        groupElement.appendChild(element);
    }
    public RichElement getNote(int index) { return notes.get(index); }
    public ArrayList<RichElement> getNotes() { return notes; }

    public void removeNote(int index) {
        notes.remove(index);
        groupElement.getElement().removeChild(index);
    }

    public Element getOrnamentExpansionElement() {
        return ornamentExpansionElement.getElement();
    }

    public RichElement getGroupElement() {
        return groupElement;
    }

    public void append(OrnamentExpansion ornamentExpansion) {
        RichElement lastNote = getNote(notes.size()-1);
        RichElement firstNote = getNote(0);

        if(lastNote.get("pname").equals(firstNote.get("pname"))
                && lastNote.get("accid.ges").equals(firstNote.get("accid.ges"))) {
            ornamentExpansion.removeNote(0);
        }

        RichElement child = ornamentExpansion.getGroupElement();
        ParentNode parent = child.getElement().getParent();
        if (parent != null) {
            parent.removeChild(child.getElement());
        }
        this.ornamentExpansionElement.appendChild(child);
        ornamentExpansionElement.set("label", ornamentExpansionElement.get("label") + ", " + child.get("label"));
    }
}
