package meico.mei.ornament;

import meico.mei.Helper;
import meico.mei.MeiNoteElement;
import nu.xom.ParentNode;

import java.util.ArrayList;

/**
 * This class represents an ornaments expansion by managing the notes to be played for this very ornament.
 * @author Lars Engeln
 */
public class OrnamentExpansion {
    private MeiNoteElement ornamentExpansionElement;
    private MeiNoteElement groupElement;
    private ArrayList<MeiNoteElement> notes;

    private ArrayList<MeiNoteElement> correspondences;
    private ArrayList<String> segmentLabels = new ArrayList<>();   // labels of individual ornament segments

    /**
     * default constructor
     */
    public OrnamentExpansion() {
        ornamentExpansionElement    = new MeiNoteElement("supplied");
        groupElement                = new MeiNoteElement("graceGrp");
        notes                       = new ArrayList<>();
        correspondences             = new ArrayList<>();

        ornamentExpansionElement.appendChild(groupElement);

        ornamentExpansionElement.set("evidence", "internal");
        ornamentExpansionElement.set("reason", "ornament expansion - generated by meico to give a basic expansion for the ornament's notes");
    }

    /**
     * sets the label for the ornament expansion and the group element
     * @param label
     */
    public void setLabel(String label) {
        ornamentExpansionElement.set("label", label);
        groupElement.set("label", label);
        if (segmentLabels.isEmpty())
            segmentLabels.add(label);
    }
    /**
     * adds a correspondence to the ornament expansion and updates the "corresp" attribute accordingly
     * @param note
     */
    public void addCorrespondence(MeiNoteElement note) {
        correspondences.add(note);
        String corresp = "";
        boolean isFirst = true;
        for (MeiNoteElement c : correspondences) {
            String id = Helper.getAttribute("id", c.getElement()).getValue();
            if (!isFirst) corresp += ' ';
            else isFirst = false;
            corresp += '#' + id;
        };

        ornamentExpansionElement.set("corresp", corresp);
    }

    /**
     * adds a note to the ornament expansion and updates its "stem.visible" attribute
     * @param element
     */
    public void addElement(MeiNoteElement element) {
        if(element.getName().equals("note")) {
            element.set("stem.visible", "false");
            notes.add(element);
        }
        groupElement.appendChild(element);
    }

    /**
     * returns the note at the given index
     * @param index
     * @return
     */
    public MeiNoteElement getNote(int index) { return notes.get(index); }

    /**
     * returns the list of notes
     * @return
     */
    public ArrayList<MeiNoteElement> getNotes() { return notes; }

    /**
     * removes the note at the given index
     * @param index
     */
    public void removeNote(int index) {
        notes.remove(index);
        groupElement.getElement().removeChild(index);
    }

    /**
     * returns the element representing the ornament expansion
     * @return
     */
    public MeiNoteElement getOrnamentExpansionElement() {
        return ornamentExpansionElement;
    }

    /**
     * returns the element representing the group of notes
     * @return
     */
    public MeiNoteElement getGroupElement() {
        return groupElement;
    }

    /**
     * appends the given ornament expansion to this one, either at the end or at the beginning, and updates the label accordingly
     * @param ornamentExpansion
     */
    public void append(OrnamentExpansion ornamentExpansion) {
        MeiNoteElement child = ornamentExpansion.getGroupElement();
        ParentNode parent = child.getElement().getParent();
        if (parent != null) {
            parent.removeChild(child.getElement());
        }
        this.ornamentExpansionElement.appendChild(child);
        ornamentExpansionElement.set("label", ornamentExpansionElement.get("label") + ", " + child.get("label"));
        segmentLabels.addAll(ornamentExpansion.getSegmentLabels());
    }

    /**
     * returns the list of individual segment labels (one per ornament that was merged into this expansion)
     * @return
     */
    public ArrayList<String> getSegmentLabels() {
        return segmentLabels;
    }
}
